// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-oRRROi7erqISkZ9pfYA6o88BVlgPaw',
    appId: '1:479867641786:android:c7c74f320df7a81c5e0783',
    messagingSenderId: '479867641786',
    projectId: 'hlt-firebase',
    storageBucket: 'hlt-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMGR7tE0D2J7Y9UDL1o9-kLzCkf8pcld8',
    appId: '1:479867641786:ios:1c3dbc5e578ee1d45e0783',
    messagingSenderId: '479867641786',
    projectId: 'hlt-firebase',
    storageBucket: 'hlt-firebase.appspot.com',
    iosBundleId: 'com.example.appbanhang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMGR7tE0D2J7Y9UDL1o9-kLzCkf8pcld8',
    appId: '1:479867641786:ios:e186ad5c8d97479c5e0783',
    messagingSenderId: '479867641786',
    projectId: 'hlt-firebase',
    storageBucket: 'hlt-firebase.appspot.com',
    iosBundleId: 'com.example.appbanhang.RunnerTests',
  );
}
